spring:
  application:
    name: msa-message-service
#  eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
#      fetch-registry: true
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
server:
  port: 9010
logging:
  level:
    root: info
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK