spring:
  config:
    activate:
      on-profile: develop
  elasticsearch:
    host: 218.146.5.48
    cluster_name: elasticsearch-master
    port: 32400
    user_name: elastic
    user_password: h2BsdptHhv6YGNb1
logging:
  level:
    org:
      spring:
        springframework:
          data:
            elasticsearch:
              client:
                WIRE: TRACE

